use crate::{KeyError, StateKey, Variable};

/// Statically selected, checked access to variables of type `T`.
///
/// Generated by [`states!`](crate::states!). Pool mutation remains solver-controlled so handles
/// and graph connectivity cannot be invalidated by direct vector edits.
pub trait StateStore<T: Variable> {
    /// Borrow the current estimate, rather than its linearization anchor.
    ///
    /// Returns an error for a removed, unknown, or foreign key.
    fn get(&self, key: StateKey<T>) -> Result<&T, KeyError>;
}

#[doc(hidden)]
pub trait StateSchema: Default {}

/// Declare a homogeneous state pool for each variable type.
///
/// Each type may appear once. Fields are private; access uses [`StateStore`].
/// The declaration generates `Default` without requiring variables to implement it.
///
/// ```no_run
/// use fagra::{states, Variable};
/// # struct Pose;
/// # impl Variable for Pose {
/// #     type Tangent = [f64; 6];
/// #     const DOF: usize = 6;
/// #     fn tangent_from_slice(_: &[f64]) -> Self::Tangent { todo!() }
/// #     fn retract(&self, _: &Self::Tangent) -> Self { todo!() }
/// # }
/// states! {
///     /// Variables used by this application.
///     SlamStates {
///         poses: Pose,
///     }
/// }
/// ```
#[macro_export]
macro_rules! states {
    ($(#[$attr:meta])* $vis:vis $name:ident {
        $($field:ident: $ty:ty),* $(,)?
    }) => {
        $(#[$attr])*
        #[derive(Default)]
        #[allow(dead_code)]
        $vis struct $name {
            $($field: ::std::vec::Vec<$ty>,)*
        }

        impl $crate::__private::StateSchema for $name {}

        $(impl $crate::StateStore<$ty> for $name {
            fn get(&self, _key: $crate::StateKey<$ty>) -> Result<&$ty, $crate::KeyError> {
                todo!("API only: checked state access")
            }
        })*
    };
}
